name: Tests
on: [push]

jobs:
  tests:
    name: Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest"]
            #os: ["macos-latest", "ubuntu-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: "latest"
          auto-activate-base: true
      - run: python -V
      - run: pip install -e .
      - run: pip install pytest
      - run: make doctests
      # - run: pip install -e .[dev]
      # - run: conda env export
      # - run: make nbtests 
